var Sponsors = {
  Brugge: [
    {
      Naam: "D-Choc",
      Straat: "Walstraat 6",
      Stad: "8000 Brugge",
      Foto: "D-Choc.jpg",
      TelefoonData: "+3250340043",
      TelefoonText: "050 34 00 43",
      Openingsuren: ["???"],
      Website: "",
      Facebook: "",
      Maps: "",
      Omschrijving: "",
      FotoCarousel: []
    },
    {
      Naam: "Cambrinus",
      Straat: "Philipstockstraat 19",
      Stad: "8000 Brugge",
      Foto: "Cambrinus.jpg",
      TelefoonData: "+3250332328",
      TelefoonText: "050 33 23 28",
      Openingsuren: ["Mon - Sun: 11AM-10PM"],
      Website: "",
      Facebook: "",
      Maps: "",
      Omschrijving: "",
      FotoCarousel: []
    },
    {
      Naam: "Cambrinus Café",
      Straat: "Philipstockstraat 7",
      Stad: "8000 Brugge",
      Foto: "CambrinusCafe.jpg",
      TelefoonData: "+3250343730",
      TelefoonText: "050 34 37 30",
      Openingsuren: ["Wed - Mon: 12-11PM", "Tue: Closed"],
      Website: "",
      Facebook: "",
      Maps: "",
      Omschrijving: "",
      FotoCarousel: []
    },
    {
      Naam: "Bourgogne Des Flandres",
      Straat: "Kartuizerinnenstraat 6",
      Stad: "8000 Brugge",
      Foto: "BourgogneDesFlandres.jpg",
      TelefoonData: "+3250335426",
      TelefoonText: "050 33 54 26",
      Openingsuren: [
        "Tue - Sun: 10:30AM-6PM / Last Visit 5PM",
        "Ale house: 10:30AM-7:30PM"
      ],
      Website: "",
      Facebook: "",
      Maps: "",
      Omschrijving: "",
      FotoCarousel: []
    },
    {
      Naam: "Mozarthuys",
      Straat: "Huidenvettersplein 1/2",
      Stad: "8000 Brugge",
      Foto: "Mozarthuys.jpg",
      TelefoonData: "+3250334530",
      TelefoonText: "050 33 45 30",
      Openingsuren: ["Sun - Thu: 10AM-10PM", "Fri - Sat: 10AM-11PM"],
      Website: "",
      Facebook: "",
      Maps: "",
      Omschrijving: "",
      FotoCarousel: []
    },
    {
      Naam: "Choco Story",
      Straat: "Wijnzakstraat 2",
      Stad: "8000 Brugge",
      Foto: "ChocoStory.jpg",
      TelefoonData: "+3250612237",
      TelefoonText: "050 61 22 37",
      Openingsuren: ["Mon - Sun: 10AM-5PM"],
      Website: "",
      Facebook: "",
      Maps: "",
      Omschrijving: "",
      FotoCarousel: []
    },
    {
      Naam: "Frietmuseum",
      Straat: "Vlamingstraat 33",
      Stad: "8000 Brugge",
      Foto: "Frietmuseum.jpg",
      TelefoonData: "+3250340150",
      TelefoonText: "050 34 01 50",
      Openingsuren: ["Mon - Sun: 10AM-5PM"],
      Website: "",
      Facebook: "",
      Maps: "",
      Omschrijving: "",
      FotoCarousel: []
    },
    {
      Naam: "Bones",
      Straat: "Sint-Jakobsstraat 7",
      Stad: "8000 Brugge",
      Foto: "Bones.jpg",
      TelefoonData: "+3250491200",
      TelefoonText: "050 49 12 00",
      Openingsuren: [
        "Mon - Thu: 5:30-11PM",
        "Fri: 5:30PM-12AM",
        "Sat - Sun: 12-3PM / 5:30-11PM"
      ],
      Website: "",
      Facebook: "",
      Maps: "",
      Omschrijving: "",
      FotoCarousel: []
    },
    {
      Naam: "Käthe Wohlfahrt",
      Straat: "Walplein 12",
      Stad: "8000 Brugge",
      Foto: "KatheWolfahrt.jpg",
      TelefoonData: "+3250330604",
      TelefoonText: "050 33 06 04",
      Openingsuren: ["Mon - Sun: 10AM-6PM"],
      Website: "",
      Facebook: "",
      Maps: "",
      Omschrijving: "",
      FotoCarousel: []
    },
    {
      Naam: "Taxi Snel",
      Straat: "Dudzeelse Steenweg 118",
      Stad: "8000 Brugge",
      Foto: "TaxiSnel.jpg",
      TelefoonData: "+3250363649",
      TelefoonText: "050 36 36 49",
      Openingsuren: ["24/7 Taxi Service"],
      Website: "",
      Facebook: "",
      Maps: "",
      Omschrijving: "",
      FotoCarousel: []
    },
    {
      Naam: "The Chocolate Crown",
      Straat: "Huidenvettersplein 13",
      Stad: "8000 Brugge",
      Foto: "ChocolateCrown.jpg",
      TelefoonData: "+3250335701",
      TelefoonText: "050 33 57 01",
      Openingsuren: ["Mon - Sun: 10AM-6PM"],
      Website: "",
      Facebook: "",
      Maps: "",
      Omschrijving: "",
      FotoCarousel: []
    },
    {
      Naam: "Top Of Bruges",
      Straat: "'t Hoogste van Brugge 1",
      Stad: "8000 Brugge",
      Foto: "QuestionMark.jpg",
      TelefoonData: "+3250xxxxxx",
      TelefoonText: "050 XX XX XX",
      Openingsuren: ["???"],
      Website: "",
      Facebook: "",
      Maps: "",
      Omschrijving: "",
      FotoCarousel: []
    },
    {
      Naam: "Tok Tok",
      Straat: "'t Hoogste van Brugge 1",
      Stad: "8000 Brugge",
      Foto: "QuestionMark.jpg",
      TelefoonData: "+3250xxxxxx",
      TelefoonText: "050 XX XX XX",
      Openingsuren: ["???"],
      Website: "",
      Facebook: "",
      Maps: "",
      Omschrijving: "",
      FotoCarousel: []
    },
    {
      Naam: "Cafedraal",
      Straat: "Zilverstraat 38",
      Stad: "8000 Brugge",
      Foto: "Cafedraal.jpg",
      TelefoonData: "+3250340845",
      TelefoonText: "050 34 08 45",
      Openingsuren: ["Mon - Sat: 12-2:45PM / 6-10:30PM", "Sun: Closed"],
      Website: "",
      Facebook: "",
      Maps: "",
      Omschrijving: "",
      FotoCarousel: []
    },
    {
      Naam: "Chagall",
      Straat: "Sint-Amandsstraat 40",
      Stad: "8000 Brugge",
      Foto: "Chagall.jpg",
      TelefoonData: "+3250336112",
      TelefoonText: "050 33 61 12",
      Openingsuren: ["Mon - Wed: 11:30AM-3PM / 5:30-9PM", "Thu: Closed"],
      Website: "",
      Facebook: "",
      Maps: "",
      Omschrijving: "",
      FotoCarousel: []
    },
    {
      Naam: "Dumon Chocolatier Eiermarkt",
      Straat: "Eiermarkt 8",
      Stad: "8000 Brugge",
      Foto: "DumonEierstraat.jpg",
      TelefoonData: "+32050346282",
      TelefoonText: "050 34 62 82",
      Openingsuren: ["Wed - Mon: 10AM-6PM", "Tue: Closed"],
      Website: "",
      Facebook: "",
      Maps: "",
      Omschrijving: "",
      FotoCarousel: []
    },
    {
      Naam: "Dumon Chocolatier Stevinplein",
      Straat: "Oude Burg 30",
      Stad: "8000 Brugge",
      Foto: "DumonSimonStevinplein.jpg",
      TelefoonData: "+32050333360",
      TelefoonText: "050 33 33 60",
      Openingsuren: ["Mon - Sun: 10AM-6:30PM"],
      Website: "",
      Facebook: "",
      Maps: "",
      Omschrijving: "",
      FotoCarousel: []
    },
    {
      Naam: "Duc De Bourgogne",
      Straat: "Huidenvettersplein 12",
      Stad: "8000 Brugge",
      Foto: "DucDeBourgogne.jpg",
      TelefoonData: "+32050332038",
      TelefoonText: "050 33 20 38",
      Openingsuren: ["Reception open 24/7"],
      Website: "",
      Facebook: "",
      Maps: "",
      Omschrijving: "",
      FotoCarousel: []
    },
    {
      Naam: "La Gondola",
      Straat: "Oude Burg 22",
      Stad: "8000 Brugge",
      Foto: "LaGondola.jpg",
      TelefoonData: "+32475489358",
      TelefoonText: "0475 48 93 58",
      Openingsuren: ["Mon - Fri: 12-2:30PM / 6-10PM", "Sat - Sun: 12-10PM"],
      Website: "",
      Facebook: "",
      Maps: "",
      Omschrijving: "",
      FotoCarousel: []
    },
    {
      Naam: "De Middenstand",
      Straat: "'t Zand 20",
      Stad: "8000 Brugge",
      Foto: "DeMiddenstand.jpg",
      TelefoonData: "+3250341750",
      TelefoonText: "050 34 17 50",
      Openingsuren: ["Thu - Fri 10AM-9PM", "Sat: 8AM-9PM", "Sun-Mon: 10AM-9PM"],
      Website: "",
      Facebook: "",
      Maps: "",
      Omschrijving: "",
      FotoCarousel: []
    },
    {
      Naam: "B&B James",
      Straat: "???",
      Stad: "8000 Brugge",
      Foto: "QuestionMark.jpg",
      TelefoonData: "+3250xxxxxx",
      TelefoonText: "050 XX XX XX",
      Openingsuren: ["???"],
      Website: "",
      Facebook: "",
      Maps: "",
      Omschrijving: "",
      FotoCarousel: []
    },
    {
      Naam: "Margritt",
      Straat: "Sint-Amandsstraat 30",
      Stad: "8000 Brugge",
      Foto: "Margritt.jpg",
      TelefoonData: "+32473358840",
      TelefoonText: "0473 35 88 40",
      Openingsuren: ["Mon - Sat: 9AM-5:30PM", "Sun: 9AM-4PM"],
      Website: "",
      Facebook: "",
      Maps: "",
      Omschrijving: "",
      FotoCarousel: []
    },
    {
      Naam: "The Laundrette by Marcel",
      Straat: "Niklaas Desparsstraat 5",
      Stad: "8000 Brugge",
      Foto: "Laundrette.jpg",
      TelefoonData: "+3250335502",
      TelefoonText: "050 33 55 02",
      Openingsuren: ["Thu - Sat: 2-9PM", "Sun: 2-7PM", "Mon - Thu: Closed"],
      Website: "",
      Facebook: "",
      Maps: "",
      Omschrijving: "",
      FotoCarousel: []
    },
    {
      Naam: "Frietfarm",
      Straat: "Zuidzandstraat 29",
      Stad: "8000 Brugge",
      Foto: "Frietfarm.jpg",
      TelefoonData: "+32471684285",
      TelefoonText: "0471 68 42 85",
      Openingsuren: ["Sun - Thu: 11AM-9PM", "Fri - Sat: 11AM-10PM"],
      Website: "",
      Facebook: "",
      Maps: "",
      Omschrijving: "",
      FotoCarousel: []
    },
    {
      Naam: "Paul's Boutique",
      Straat: "Sint-Amandsstraat 22",
      Stad: "8000 Brugge",
      Foto: "PaulBoutique.jpg",
      TelefoonData: "+3250737411",
      TelefoonText: "050 73 74 11",
      Openingsuren: ["Mon - Thu: 12-9PM", "Fri-Sat: 12-10PM", "Sun: Closed"],
      Website: "",
      Facebook: "",
      Maps: "",
      Omschrijving: "",
      FotoCarousel: []
    },
    {
      Naam: "Eat-Thai",
      Straat: "Oude Burg 10",
      Stad: "8000 Brugge",
      Foto: "EatThai.jpg",
      TelefoonData: "+3250660626",
      TelefoonText: "050 66 06 26",
      Openingsuren: ["Thu - Mon: 12-3PM / 6-10PM", "Tue - Wed: Closed"],
      Website: "",
      Facebook: "",
      Maps: "",
      Omschrijving: "",
      FotoCarousel: []
    },
    {
      Naam: "Lokkedize",
      Straat: "Korte Vuldersstraat 33",
      Stad: "8000 Brugge",
      Foto: "Lokkedize.jpg",
      TelefoonData: "+32496692662",
      TelefoonText: "0496 69 26 62",
      Openingsuren: ["Thu - Mon: 6PM-1AM", "Tue - Wed: Closed"],
      Website: "",
      Facebook: "",
      Maps: "",
      Omschrijving: "",
      FotoCarousel: []
    },
    {
      Naam: "Diamond Museum",
      Straat: "Katelijnestraat 43",
      Stad: "8000 Brugge",
      Foto: "Diamantmuseum.jpg",
      TelefoonData: "+3250342056",
      TelefoonText: "050 34 20 56",
      Openingsuren: ["Mon - Sun: 10:30AM - 5:30PM"],
      Website: "",
      Facebook: "",
      Maps: "",
      Omschrijving: "",
      FotoCarousel: []
    }
  ]
};
